apiVersion: consul.hashicorp.com/v1alpha1
kind: PeeringAcceptor
metadata:
  name: cluster-02 ## The name of the peer you want to connect to
  annotations:
    consul.hashicorp.com/peering-version: "1"
spec:
  peer:
    secret:
      name: "peering-token"
      key: "data"
      backend: "kubernetes"
